from __future__ import annotations

"""Auth dependency — validates X-API-Key (RapidAPI-forwarded) or Bearer token.

Returns the caller's tier, which drives rate limits + feature gates.

Tier resolution (in priority order):
  1. Direct-site dev/admin keys in ``_KEY_TIER`` (the PERMY_API_KEYS path) —
     highest priority, used for the direct site, MCP server, and tests.
  2. ``X-RapidAPI-Subscription`` header — the plan name RapidAPI's gateway
     forwards when a buyer subscribes on the Hub. This is how we know which
     tier they *paid* for. Values: BASIC | PRO | ULTRA | MEGA | CUSTOM.
     Mapped to internal tiers via ``_RAPIDAPI_SUBSCRIPTION_TIER``.
  3. Fallback: ``free`` — so a brand-new RapidAPI subscriber (or any unknown
     caller through the gateway) still gets a working free-tier response
     rather than a hard reject. RapidAPI enforces its own quotas at the
     gateway on top of this.

API keys are generated by RapidAPI, not by us. We never store or provision
customer keys — the gateway forwards them in ``X-RapidAPI-Key``.
"""
from typing import Optional  # noqa: E402

from fastapi import Header, HTTPException, Request, status  # noqa: E402

from permy.core.config import TIER_LIMITS, settings  # noqa: E402
from permy.core.logging import logger  # noqa: E402

# Direct-site keys (PERMY_API_KEYS / PERMY_ADMIN_KEYS env) → tier. Used for the
# direct site, MCP server, tests, and any caller presenting one of these.
# SECURITY: never hardcode keys here. The repo is PUBLIC — any committed key is
# a free enterprise-tier backdoor. Keys are loaded from env at import time; if
# the env is empty (local dev default), only the RapidAPI subscription path runs.
def _load_key_tier_map() -> dict:
    """Build {key: tier} from env so no key is ever hardcoded in source.

    PERMY_API_KEYS supports an optional ``key:tier`` suffix so tests and the
    direct site can simulate tiers without leaking prod keys:
        PERMY_API_KEYS=dev-key-1:free,dev-key-2:pro
    Keys without a ``:tier`` suffix default to ``free``. PERMY_ADMIN_KEYS
    entries always map to ``enterprise`` (unlimited), regardless of suffix.

    SECURITY: the legacy hardcoded keys (dev-key-1, dev-key-2, admin-key-1,
    ci-key) were removed because the repo is PUBLIC — any committed key was a
    free enterprise-tier backdoor. Set these via env in the deployed environment.
    """
    valid_tiers = set(TIER_LIMITS.keys())
    # SAFE-BY-DEFAULT: in prod/staging, ignore the dev-default key string unless
    # the operator explicitly set PERMY_API_KEYS in the environment. Otherwise a
    # public-repo reader could send X-API-Key: dev-key-2 and get Pro tier for
    # free. Prod should rely on the RapidAPI X-RapidAPI-Subscription header.
    raw = settings.api_keys
    _DEV_DEFAULT = "dev-key-1:free,dev-key-2:pro"
    if settings.env in ("prod", "production", "staging") and raw.strip() == _DEV_DEFAULT:
        raw = ""
    m: dict = {}
    for entry in raw.split(","):
        entry = entry.strip()
        if not entry:
            continue
        if ":" in entry:
            key, _, tier = entry.partition(":")
            key, tier = key.strip(), tier.strip().lower()
            m[key] = tier if tier in valid_tiers else "free"
        else:
            m[entry] = "free"
    for k in settings.admin_key_set:
        m[k] = "enterprise"  # admin keys → unlimited
    return m


_KEY_TIER = _load_key_tier_map()

# RapidAPI plan name (X-RapidAPI-Subscription) → internal tier.
# RapidAPI's Monetize tab exposes at most 4 plans; we name them BASIC/PRO/ULTRA/MEGA
# to match the hub, and map them to internal tiers. Match these to the plans you
# create in the RapidAPI Monetize tab — see docs/RAPIDAPI_LISTING.md. If you rename
# a plan on RapidAPI, update the key here to match exactly (case-insensitive).
_RAPIDAPI_SUBSCRIPTION_TIER = {
    "basic": "free",        # BASIC  — $0,   100/day
    "pro": "builder",       # PRO    — $49,  10,000/mo   (RapidAPI "PRO" → our builder)
    "ultra": "pro",         # ULTRA  — $149, 100,000/mo  (leads + intel + webhooks)
    "mega": "business",     # MEGA   — $499, 500,000/mo  (bulk + multi-key + SLA + MCP)
    "custom": "business",   # Custom private plan — treat as business unless overridden
}


class ApiKeyContext:
    def __init__(self, key: str, tier: str):
        self.key = key
        self.tier = tier
        self.limits = TIER_LIMITS[tier]

    @property
    def can_webhooks(self) -> bool:
        return bool(self.limits["webhooks"])

    @property
    def can_export(self) -> bool:
        return bool(self.limits["export"])

    @property
    def can_leads(self) -> bool:
        return bool(self.limits["leads"])

    @property
    def can_intel(self) -> bool:
        return bool(self.limits["intel"])


def _extract_key(
    x_api_key: Optional[str],
    authorization: Optional[str],
) -> Optional[str]:
    if x_api_key:
        return x_api_key.strip()
    if authorization and authorization.lower().startswith("bearer "):
        return authorization[7:].strip() or None
    return None


def get_api_key_context(
    request: Request,
    x_api_key: Optional[str] = Header(None, alias="X-API-Key"),
    authorization: Optional[str] = Header(None),
):
    # No return annotation: FastAPI must NOT treat ApiKeyContext as a response model.
    # RapidAPI forwards the subscriber key in X-RapidAPI-Key too
    rapid_key = request.headers.get("x-rapidapi-key")
    key = _extract_key(x_api_key, authorization) or (rapid_key.strip() if rapid_key else None)
    if not key:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail={"error": {
                "code": "missing_api_key",
                "message": "Provide X-API-Key header (or Authorization: Bearer).",
                "docs_url": "https://docs.permy.dev/auth",
            }},
        )
    # ---- Tier resolution (priority order) ----
    # 1. Direct-site / dev keys in _KEY_TIER take precedence (tests, direct site, MCP).
    tier = _KEY_TIER.get(key)
    if tier is None:
        # 2. RapidAPI path: resolve the tier from the plan the buyer subscribed to.
        #    RapidAPI's gateway forwards X-RapidAPI-Subscription = BASIC|PRO|ULTRA|...
        #    This is the ONLY reliable way to know what they paid for — the key
        #    alone is just an identity, not a tier.
        sub = request.headers.get("x-rapidapi-subscription")
        if sub:
            sub_norm = sub.strip().lower()
            tier = _RAPIDAPI_SUBSCRIPTION_TIER.get(sub_norm)
            if tier is None:
                # Unmapped plan name — log for visibility so we notice when RapidAPI
                # renames/adds a plan before wiring it into _RAPIDAPI_SUBSCRIPTION_TIER.
                # Fallback to free is safe: RapidAPI still enforces gateway quotas.
                logger.warning("unmapped_rapidapi_subscription",
                               extra={"subscription": sub_norm})
        # 3. Fallback: free. A brand-new RapidAPI subscriber (or any caller we
        #    haven't mapped) gets a working free-tier response. RapidAPI also
        #    enforces its own quotas at the gateway, so this is safe.
        if tier is None:
            tier = "free"
    ctx = ApiKeyContext(key=key, tier=tier)
    request.state.api_key = key
    request.state.tier = tier
    return ctx


def require_feature(feature: str):
    """Dependency factory: gates an endpoint behind a tier feature flag.

    The inner callable has no return annotation, so FastAPI won't try to treat
    ApiKeyContext as a response model.
    """
    def _check(request: Request,
               x_api_key: Optional[str] = Header(None, alias="X-API-Key"),
               authorization: Optional[str] = Header(None)):
        ctx = get_api_key_context(request, x_api_key, authorization)
        if not getattr(ctx, f"can_{feature}", False):
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail={"error": {
                    "code": "feature_not_available",
                    "message": f"'{feature}' requires a higher tier. Upgrade at https://rapidapi.com/permy.",
                    "docs_url": "https://docs.permy.dev/pricing",
                }},
            )
        return ctx
    _check.__name__ = f"require_{feature}"
    return _check
