from __future__ import annotations

"""Auth dependency — validates X-API-Key (RapidAPI-forwarded) or Bearer token.

Returns the caller's tier, which drives rate limits + feature gates.

Tier resolution (in priority order):
  1. Direct-site dev/admin keys in ``_KEY_TIER`` (the PERMY_API_KEYS path) —
     highest priority, used for the direct site, MCP server, and tests.
  2. ``X-RapidAPI-Subscription`` header — the plan name RapidAPI's gateway
     forwards when a buyer subscribes on the Hub. This is how we know which
     tier they *paid* for. Values: BASIC | PRO | ULTRA | MEGA | CUSTOM.
     Mapped to internal tiers via ``_RAPIDAPI_SUBSCRIPTION_TIER``.
  3. Fallback: ``free`` — so a brand-new RapidAPI subscriber (or any unknown
     caller through the gateway) still gets a working free-tier response
     rather than a hard reject. RapidAPI enforces its own quotas at the
     gateway on top of this.

API keys are generated by RapidAPI, not by us. We never store or provision
customer keys — the gateway forwards them in ``X-RapidAPI-Key``.
"""
from typing import Optional

from fastapi import Header, HTTPException, Request, status

from permy.core.config import TIER_LIMITS, settings

# Direct-site keys (the PERMY_API_KEYS path) → tier. Used for the direct site,
# MCP server, tests, and any caller presenting one of these. In production,
# PERMY_API_KEYS contains your own direct-site key(s); RapidAPI subscriber keys
# are NOT listed here — they're identified via the subscription header below.
_KEY_TIER = {
    "dev-key-1": "free",
    "dev-key-2": "pro",
    "admin-key-1": "enterprise",
    "ci-key": "pro",
}

# RapidAPI plan name (X-RapidAPI-Subscription) → internal tier.
# RapidAPI sends BASIC | PRO | ULTRA | MEGA | CUSTOM (case-insensitive).
# Match these to the plans you create in the RapidAPI Monetize tab — see the
# mapping notes in docs/RAPIDAPI_LISTING.md. If you rename a plan on RapidAPI,
# update the key here to match exactly (case-insensitive).
_RAPIDAPI_SUBSCRIPTION_TIER = {
    "basic": "free",        # Free tier — $0, 100/day
    "starter": "starter",   # Starter — $19/mo (name your RapidAPI plan "STARTER")
    "builder": "builder",   # Builder — $49/mo (name your RapidAPI plan "BUILDER")
    "pro": "pro",           # Pro — $149/mo, unlocks leads + intel + webhooks
    "ultra": "business",    # Ultra — $499/mo (RapidAPI's ULTRA → our business tier)
    "mega": "enterprise",   # Mega — enterprise/SLA
    "custom": "business",   # Custom private plan — treat as business unless overridden
}


class ApiKeyContext:
    def __init__(self, key: str, tier: str):
        self.key = key
        self.tier = tier
        self.limits = TIER_LIMITS[tier]

    @property
    def can_webhooks(self) -> bool:
        return bool(self.limits["webhooks"])

    @property
    def can_export(self) -> bool:
        return bool(self.limits["export"])

    @property
    def can_leads(self) -> bool:
        return bool(self.limits["leads"])

    @property
    def can_intel(self) -> bool:
        return bool(self.limits["intel"])


def _extract_key(
    x_api_key: Optional[str],
    authorization: Optional[str],
) -> Optional[str]:
    if x_api_key:
        return x_api_key.strip()
    if authorization and authorization.lower().startswith("bearer "):
        return authorization[7:].strip() or None
    return None


def get_api_key_context(
    request: Request,
    x_api_key: Optional[str] = Header(None, alias="X-API-Key"),
    authorization: Optional[str] = Header(None),
):
    # No return annotation: FastAPI must NOT treat ApiKeyContext as a response model.
    # RapidAPI forwards the subscriber key in X-RapidAPI-Key too
    rapid_key = request.headers.get("x-rapidapi-key")
    key = _extract_key(x_api_key, authorization) or (rapid_key.strip() if rapid_key else None)
    if not key:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail={"error": {
                "code": "missing_api_key",
                "message": "Provide X-API-Key header (or Authorization: Bearer).",
                "docs_url": "https://docs.permy.dev/auth",
            }},
        )
    # ---- Tier resolution (priority order) ----
    # 1. Direct-site / dev keys in _KEY_TIER take precedence (tests, direct site, MCP).
    tier = _KEY_TIER.get(key)
    if tier is None:
        # 2. RapidAPI path: resolve the tier from the plan the buyer subscribed to.
        #    RapidAPI's gateway forwards X-RapidAPI-Subscription = BASIC|PRO|ULTRA|...
        #    This is the ONLY reliable way to know what they paid for — the key
        #    alone is just an identity, not a tier.
        sub = request.headers.get("x-rapidapi-subscription")
        if sub:
            tier = _RAPIDAPI_SUBSCRIPTION_TIER.get(sub.strip().lower())
        # 3. Fallback: free. A brand-new RapidAPI subscriber (or any caller we
        #    haven't mapped) gets a working free-tier response. RapidAPI also
        #    enforces its own quotas at the gateway, so this is safe.
        if tier is None:
            tier = "free"
    ctx = ApiKeyContext(key=key, tier=tier)
    request.state.api_key = key
    request.state.tier = tier
    return ctx


def require_feature(feature: str):
    """Dependency factory: gates an endpoint behind a tier feature flag.

    The inner callable has no return annotation, so FastAPI won't try to treat
    ApiKeyContext as a response model.
    """
    def _check(request: Request,
               x_api_key: Optional[str] = Header(None, alias="X-API-Key"),
               authorization: Optional[str] = Header(None)):
        ctx = get_api_key_context(request, x_api_key, authorization)
        if not getattr(ctx, f"can_{feature}", False):
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail={"error": {
                    "code": "feature_not_available",
                    "message": f"'{feature}' requires a higher tier. Upgrade at https://rapidapi.com/permy.",
                    "docs_url": "https://docs.permy.dev/pricing",
                }},
            )
        return ctx
    _check.__name__ = f"require_{feature}"
    return _check
